Telecominfraproject/wlan-ap

feeds/network/services/opensync/Makefile
opensync/platform/openwrt/src/lib/target/src/stats.c

On channel background scan functionality added

---

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/stats.c
feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/stats_nl80211.c
feeds/wlan-ap/opensync/src/vendor/tip/src/lib/target/inc/target_tip.h

WIFI-1105: Bug fix for survey report per radio

---

feeds/wifi-ax/mac80211/files/lib/wifi/mac80211.sh

Signed-off-by: Rick Sommerville <rick.sommerville@netexperience.com>

WIFI-1240 Remove default SSID on 802.11ax radios

---

patches/0039-Add-usr-bin-get_tip-script-for-EC420.patch

Signed-off-by: Rick Sommerville <rick.sommerville@netexperience.com>

WIFI-1032 Repair EC420 MAC retrieval from manufacturing data

---

feeds/wlan-ap/opensync/patches/24-channels-state.patch
feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/inc/phy.h
feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c
feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio_nl80211.c
feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/utils.c

Wifi-886 : Channels field in radio state table populated
Signed-off-by: Ammad Rehmat <ammad.rehmat@connectus.ai>

Wifi-886 : Channels field in radio state table populated

---

feeds/wlan-ap/nft-qos/files/lib/mac-rate.sh
feeds/wlan-ap/nft-qos/files/lib/ssid_ratelimit.sh
feeds/wlan-ap/opensync/files/etc/hotplug.d/net/40-rlimit-ssid

opensync: fix ssid-ratelimiting

---

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio_nl80211.c

Query the driver and update the wifi_associated_clients list
during wm initialization.

wifi-3301:Sync Wifi_associated_Clients if opensync restarts

---

patches/0058-Fix-mac-assign-on-ath11k.patch

Port over mac assign fix from v2.

WIFI-3023: fix mac assign on ath11k

---

patches/0063-Add-reset-button-for-wf194c-and-wf188n.patch

Add reset button for wf194c and wf188n APs

Add reset button for wf194c and wf188n

---

feeds/wlan-ap/opensync/src/platform/openwrt/src/command/src/node_config.c

Add capability to turn on/off LEDs.

WIFI-4322: add capability to turn on/off LEDs

---

feeds/wlan-ap/opensync/src/platform/openwrt/src/command/src/node_config.c

This patch will fix EC420 AP LED color change issue

WIFI-4474-EC420-LED-Colour-Config

---

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/vif.c

This patch will fix the client blocked list update issue

WIFI-4473-Client-Blocked-List

---

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c

WIFI-5291-APC-config-reload

---

patches/0064-ipq4019-Single-PHY-VLAN-Fix.patch

Signed-off-by: Siddharth Pandey <siddharth.pandey@vvdntech.com>

ipq4019: Single PHY VLAN Fix.

---

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c

A channel change request from RRM while a reload_config is in
progress cause the new CSA attempt fail. AP updated the UCI
no matter if the CSA attempt failed or passed. This leads to
the AP not re-trying the CSA again.
Furthermore another issue is seen when an invalid channel/BW
combination is configured. Solution is to update the Bandwidth
as per channel change request is made via CSA.
Example: BW already configured for 40MHz, and then the channel
change attempt is made to 165. The channel change code takes care
of downgrading the BW to 20MHz while sending the request down to
the driver, but did not update the same in the UCI config.
UCI config reads as 165/40. A reloadconfig thereafter causes this
invalid combination 165/40 attempt which leads to radio stay disabled.
Signed-off-by: ravi …

Wifi-5995. Fix for CSA failure and invalid chan/BW config

---

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c

In case of full config push, do not send CSA as hostapd
is anyway going to reload with reload_config script detecting
the UCI change. This would help avoid double channel switch.
Signed-off-by: Yashvardhan <yashvardhan@netexperience.com>

wifi-6062: Fix for CAC timer running twice

---

.github/workflows/build-dev.yml

- allows to apply S3 lifecycle rules

add release tag to S3 objects

---

feeds/ipq807x/ipq807x/base-files/etc/board.d/02_network
feeds/wifi-ax/mac80211/patches/pending/211-replace_txq0.patch

Merging changes from main to release/v2.7.0
Signed-off-by: Jaspreet Sachdev <jaspreetsachdev@fb.com>

Fixes for WIFI-11004

---

.github/workflows/build-dev.yml

Signed-off-by: John Crispin <john@phrozen.org>
Signed-off-by: Jaspreet Sachdev <jaspreetsachdev@meta.com>

.github: add wallys_dr6018_v4 to the build pipeline

---

feeds/mediatek-sdk/mediatek/patches-5.4/999-eap111-eap112-eth.patch

mediatek: Fix MAC assignment for eth ports on Edgecore EAP112
