feeds/wlan-ap/opensync/patches/23-ax-options.patch, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/vif.c
opensync: add HE parameters to data model
This patch adds support for pushing the new HE options down from the cloud
and rendering them out into uci.
Signed-off-by: John Crispin <john@phrozen.org>
=> opensync: add HE parameters to data model

feeds/wlan-ap/opensync/src/src/sm/src/ubus_collector.c
NETEXP-612 : Client reported against wrong radio
NETEXP-733 : Wrong number of clients reported
Fix : Radio band was not correctly extracted from blobmsg received from hostapd. Data type fixed from u8 to u32
Signed-off-by: Ammad Rehmat <ammad.rehmat@connectus.ai>
=> Client events

feeds/wlan-ap/opensync/src/platform/openwrt/src/netifd/src/dhcp.c
Configure dnsmasq init to override devstatus carrier check.
Fixes WIFI-1148
Signed-off-by: Arif Alam <arif.alam@connectus.ai>
=> opensync: fix NAT clients not getting IP

feeds/wlan-ap/opensync/src/platform/openwrt/rootfs/common/etc/init.d/opensync
Not all opensync managers were terminated on service stop/restart.
Send SIGKILL to terminate all managers.
=> opensync: terminate all managers on service stop/restart

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/inc/utils.h, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/utils.c
- AP was not reporting the Channel Tx power currently set in
the firmware. This patch reads the Tx power from debugFS stats
and reports it to cloud through Wifi_Radio_State table
Signed-off-by: Yashvardhan <yashvardhan@netexperience.com>
=> Wifi-3309: Fix Tx power reporting

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/stats.c
The data from the chan_info events were overwriting the data
to the existing survey info counters. The data in the chan_info
events were Read-On-Clear where as the Survey info was maintained
as incremental stats and the application in the User space
performs the calculations based on incremental survey info stats.
As an example, the survey->time was always stored as 150 due to
chan_info event's Clear-On-Read nature. And this lead to the
difference calcuation as 0 at the User space application.
Solution is to add the incoming chan_info data to the existing
survey info stats, instead of replacing the existing data with new.
=> Wifi-3246. Add chan_info data to existing survey info data

patches/0059-wifi-3258-Fix-bridge-client-traffic-on-same-wifi-interface.patch
Allow bridging broadcast and multicast traffic within same
bridge port if hairpinmode is enabled for that port.
This fixes the ARP packet between clients on same wifi interface
being dropped.
=> wifi-3258: Fix bridge client traffic on same wifi interface

patches/0060-wifi-3244-wf610d-config-reset-over-sysupgrade.patch
This patch will fix configuration restore problem over sysupgrade
on WF610D
Even though there is a configuration data in the /dev/mtdblock12, it is getting erased while reading it beacuse of JFFS2 empty bitmask code. So I added a condition to check whether the datatype available is JFFS2 or not, and making sure it is not empty before returning the JFFS2 flag to restore the configuration.
=> WIFI-3244-WF610D-Config-Reset-Over-Sysupgrade

feeds/wlan-ap/opensync/patches/43-sm_validate_noise_floor.patch, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/stats_nl80211.c
Sometimes, the driver reports 0 Noise Floor value which is
not a valid data point. Adding a workaround in Opensync layer
to consider previous recorded NF value when 0 NF is reported.
=> Wifi-3490. Opensync workaround for 0 NF reported.

patches/0061-fix-radio-down.patch
Added commits from openwrt 21.x to try and address the 5G going down issue.
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=d515f6b6cde357bf480d32a7387f07ea40e85e52
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=3933e29d1b87c713167cf4730b68e5f18af4f140
Doesn't seem to fix the issue where the 5G radio goes down when we update the AP's config. But Yong did notice that it helped with the situation where the 5G radio would go down when running traffic for an extended period of time.
=> WIFI-2844: Added patch from openwrt commits

feeds/wlan-ap/opensync/patches/42-sm_dbg_log.patch, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/stats_nl80211.c
Correcting an earlier commit 4beda3ab6607825639f9c018456a83a8e79f2d72
to consider all the cases where the avl entry needs be deleted when
a scan is either completed or aborted for any reason.
=> Wifi-3522. Correcting an earlier commit for scan failures.

feeds/wifi-ax/hostapd/patches/f00-020-dont-enable-hairpin-in-x_snoop.patch, feeds/wifi-trunk/hostapd/patches/909-dont-enable-hairpin-in-x_snoop.patch
Dont enable hairpin mode from hostapd (x_snoop) as it overwrites
the set value by netifd to enable/disable client isolation.
=> wifi-3888: Fix for Client Local access enable/disable

patches/0063-Allow-DHCP-broadcast-packets.patch
This patch will add fix to allow DHCP broadcast packets, so that AP can forward DHCP broadcast offer to clients
Cause:
In the bridge source code, there is a mechanism to drop all the broadcast packets if the proxy arp is enabled, because of this dhcp clients which set broadcast flag to 1 while connecting toAP's interfaces are not able get an ip address hence they are not connecting
Solution:
Added the code to the bridge source code so that before dropping broadcast packets it first checks, whether it is dhcp broadcast packet or not. So that it won't drop dhcp braodcast packets.Hence DORA process will succeed and clients which sets broadcast flag to 1 gets an ip address even though the proxy arp is enabled.
=> WIFI-3905-WIFI5-AP does not forward dhcp broadcast offer

patches/0062-Allow-DHCP-Broadcast-packets.patch
This patch will add fix to allow DHCP broadcast packets,
so that WIFI6 AP can forward DHCP broadcast offer to clients
Cause:
In the bridge source code, there is a mechanism to drop all the broadcast packets if the proxy arp is enabled, because of this dhcp clients which set broadcast flag to 1 while connecting toAP's interfaces are not able get an ip address hence they are not connecting
Solution:
Added the code to the bridge source code so that before dropping broadcast packets it first checks, whether it is dhcp broadcast packet or not. So that it won't drop dhcp braodcast packets.Hence DORA process will succeed and clients which sets broadcast flag to 1 gets an ip address even though the proxy arp is enabled.
=> WIFI-3905-WIFI6-AP does not forward dhcp broadcast offer

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c
Apply maverick ssid config after timeout.
=> WIFI-4209: Fix Maverick SSID

feeds/wlan-ap/opensync/patches/44-sm_set_min_sig_neighbour_report.patch
Added a check to filter out SSID's with a low signal from out neighbour reports. Removes neighbours that have a RSSI value below the minimum value for that radio type. 
Signed-off-by: Owen Anderson <owenthomasanderson@gmail.com>
=> WIFI-2410: Filter out low signal SSID from SM neighbour report

feeds/wlan-ap/opennds/patches/02-display-ssid-name-on-splash-page-instead-wlan-name.patch
This patch will add support to display ssid name on the captive portal
splash page
=> WIFI-4229-display-ssid-name-on-CP-splash-page

feeds/wifi-ax/hostapd/patches/f00-021-chan-switch-check-dfs-channel-availability.patch, feeds/wifi-trunk/hostapd/patches/910-chan-switch-check-dfs-channel-availability.patch, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/inc/fixup.h, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/inc/rrm_config.h, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/fixup.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/rrm_config.c
On detecting Radar on the DFS channel the radio switches
the channel to backup channel. However, the opensync tries
to set it back to the configured channel every 30 seconds, which
which would fail since the channel is in a radar NOP period, this
leads to dropping of clients.
Fix by adding a check for the configured channel's availability
before trying to change to that channel.
=> wifi-4421: Fix client disconn when in DFS channel

feeds/wlan-ap/opensync/src/platform/openwrt/src/netifd/src/wifi_inet_config.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/netifd/src/wifi_inet_state.c
Fix by adding LAN port check in case of single ethernet
port APs where LAN port is not available.
=> wifi-4651: Fix NM crash in single ethernet port APs

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/inc/radio.h, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio_nl80211.c
Updating the Opensync radioState allowed channels list
and the band column after a country code change.
=> Wifi-4638. update allowed channels and band in radioState

feeds/wlan-ap/opensync/patches/46-add-channel-bandwidth-to-survey-sample.patch, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/inc/target_OPENWRT.h, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/inc/utils.h, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/stats.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/utils.c, feeds/wlan-ap/opensync/src/vendor/tip/src/lib/target/inc/target_tip.h
Current survey sample report doesn't include channel bandwidth parameter, hence cloud won't be having channel bandwidth information.
This patch will add support to add channel bandwidth attribute to survey sample report and will report available channel
bandwidth on respective channel to the cloud.
=> WIFI-4924-Report-Channel-Bandwidth

feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/radio.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/netifd/src/wifi_inet_config.c, feeds/wlan-ap/opensync/src/platform/openwrt/src/netifd/src/wifi_inet_state.c, feeds/wlan-ap/wlan-ap-config/files/etc/hotplug.d/iface/30-eth-vlan
Fix ethernet port vlan access mode in wifi6
Create a vlan bridge and attach wan vlan interface
and eth port in the vlan bridge.
=> wifi-5624: Fix eth port VLAN Access in wifi6

feeds/wlan-ap/modules/nf_uccdetect/src/nf_uccdetect.c
nf_uccdetect module tries and analyze the traffic to detect
VoIP calls, and generate events up to the user space. This module
assigns value -1 as RadioID for packets from Ethernet interface
which eventually is used as an array index, eventually running
into an Assert and crash. Fix is to skip these packets from
Ethernet interface for the analysis.
=> Wifi-5798. Fix for SM crash during VoIP calls

patches/0068-Importing-missing-fixes-for-EAP102.patch
Bringing in the missing changes from a patch which was earlier
committed on Pennding and which got over-written with CS merge.
=> Wifi-6129. Fix for client connectivity with EAP102 VLAN

feeds/wlan-ap/opensync/src/platform/openwrt/src/command/src/node_config.c
Fix cmdm crash when LED definition is not present in board.json.
=> WIFI-6180: Fix cmdm crash

feeds/ipq807x/qca-nss-clients/Makefile
Update qca-nss-clients feed source url to fix build failure.
=> ipq807x: fix qca-nss-clients feed
